### ISSUE TITLE
OIT sample has no article and no real description in its readme

### ISSUE THREAD

**Issue by huawei-ahcox** [GameTechDev/AOIT-Update#1]
It is quite hard to evaluate the sample without any description of what technique it implements: OIT comes in many flavours.

**Comment by DaveBookout-Intel** [comment]
i've updated the read me with information that was originally posted here: https://software.intel.com/content/www/us/en/develop/articles/oit-approximation-with-pixel-synchronization.html.

the sample uses rasterizer order views to store transparency information per pixel in something like an A-Buffer with a fixed size of samples per pixel.
